//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqliteAutomiser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFCONNSTRING {
            get {
                return ((string)(this["DEFCONNSTRING"]));
            }
            set {
                this["DEFCONNSTRING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFSQLFILEDIR {
            get {
                return ((string)(this["DEFSQLFILEDIR"]));
            }
            set {
                this["DEFSQLFILEDIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string IMPORTDECIMALSEPARATOR {
            get {
                return ((string)(this["IMPORTDECIMALSEPARATOR"]));
            }
            set {
                this["IMPORTDECIMALSEPARATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFIMPORTDIR {
            get {
                return ((string)(this["DEFIMPORTDIR"]));
            }
            set {
                this["DEFIMPORTDIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFEXPORTDIR {
            get {
                return ((string)(this["DEFEXPORTDIR"]));
            }
            set {
                this["DEFEXPORTDIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EXPORTCOLUMNNAMES {
            get {
                return ((bool)(this["EXPORTCOLUMNNAMES"]));
            }
            set {
                this["EXPORTCOLUMNNAMES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string EXPORTSEPARATOR {
            get {
                return ((string)(this["EXPORTSEPARATOR"]));
            }
            set {
                this["EXPORTSEPARATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFCONNSTRING_OPT {
            get {
                return ((string)(this["DEFCONNSTRING_OPT"]));
            }
            set {
                this["DEFCONNSTRING_OPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public char IMPORTCOLUMNSEPARATOR {
            get {
                return ((char)(this["IMPORTCOLUMNSEPARATOR"]));
            }
            set {
                this["IMPORTCOLUMNSEPARATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sqliteautomiser_log.txt")]
        public string LOGFILE {
            get {
                return ((string)(this["LOGFILE"]));
            }
            set {
                this["LOGFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBPATH {
            get {
                return ((string)(this["DBPATH"]));
            }
            set {
                this["DBPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>,</string>\r\n  <string>TAB</string>\r\n  <string>;</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection SEPARATOROPTIONS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SEPARATOROPTIONS"]));
            }
            set {
                this["SEPARATOROPTIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>csv</string>\r\n  <string>db</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EXPORTTYPEOPTIONS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EXPORTTYPEOPTIONS"]));
            }
            set {
                this["EXPORTTYPEOPTIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EXPORTTYPE {
            get {
                return ((string)(this["EXPORTTYPE"]));
            }
            set {
                this["EXPORTTYPE"] = value;
            }
        }
    }
}
